version: "3"
services:
  postgres:
    image: postgres:14
    container_name: lab-api-db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - production-network
    ports:
      - "5432:5432"
  api:
    image: labestudo/api:latest
    container_name: lab-api
    build:
      dockerfile: Dockerfile
      context: ./api
    networks:
      - production-network
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MAIL_USER 
      - MAIL_PASS 
networks:
  production-network:
    driver: bridge