version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: lab-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-db
    networks:
      - production-network
    ports:
      - "5432:5432"
  api:
    image: labestudo/api:latest
    container_name: lab-api
    networks:
      - production-network
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: lab-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      MAIL_USER: labestudo2021@gmail.com
      MAIL_PASS: Lab#2021@
networks:
  production-network:
    driver: bridge