name: Build & Test Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build application
      - uses: actions/checkout@v2
      - name: Set up JDK 11
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
      - run: mvn -B package --file api/pom.xml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: run unit/integration tests
      - uses: actions/checkout@v2
      - name: Set up JDK 11
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run tests with Maven
      - run: mvn clean verify
    
